version: "3"

services:
  server:
    build:
      context: .
      args:
        PORT: 8080
    ports:
      - 8080:8080
    command: ["server"]
  websocket_server:
    build:
      context: .
      args:
        PORT: 5678
    ports:
      - 5678:5678
    environment:
      - WEBSOCKET_PORT=5678
      - STRING_LENGTH=32
      - UPDATE_INTERVAL=1
    command: ["websocket_server"]
    
